language: php

env:
  global:
    - excludegroup=travis-ci-exclude
    - disable-xdebug=true

git:
  depth: 2

matrix:
  include:
    - php: hhvm
      env: disable-xdebug=false
    - php: nightly
      env: disable-xdebug=false
    - php: 7.1
      env: disable-xdebug=false
    - php: 7.0
    - php: 5.6
      env: excludegroup=travis-ci-exclude-56

  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

notifications:
  email: false

before_script:
  - if [[ $disable-xdebug = true ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload --optimize

script:
  # Use custom script to avoid the risk of terminating the build process
  - ./bin/travis/fail-non-feature-topic-branch-pull-request
  # Verify application version and Git tag match on tagged builds
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
      composer lpv:application-version-guard;
    fi
  - composer lpv:cs-lint
  - if [[ $excludegroup = travis-ci-exclude ]]; then
      composer lpv:test -- --exclude-group travis-ci-exclude;
    fi
  - if [[ $excludegroup = travis-ci-exclude-56 ]]; then
      composer lpv:test -- --exclude-group travis-ci-exclude-56;
    fi
